### ISSUE TITLE
Unusual fstab highlighting

### ISSUE THREAD

**Issue by rpigott** [rid9/vim-fstab#7]
My valid fstab is highlighted unusually by vim:

```
/dev/mapper/root  /           btrfs  rw,noatime,space_cache=v2,subvol=/subroot
/dev/mapper/root  /top        btrfs  rw,noatime,subvol=/,noauto
/dev/mapper/root  /home       btrfs  rw,noatime,subvol=/home
/dev/mapper/root  /media      btrfs  rw,noatime,subvol=/media
/dev/mapper/root  /var/cache  btrfs  rw,noatime,subvol=/cache
/dev/mapper/root  /var/log    btrfs  rw,noatime,subvol=/log
/dev/mapper/root  /var/tmp    btrfs  rw,noatime,subvol=/tmp
```

The optional freq and passno fields are left empty.

vim highlights all of the option fields as errors even though they are correct. Curiously, adding a trailing space removes the error highlighting. Additionally, changing the number of spaces between the type field and options field also removes the error highlighting, but produces different (incorrect?) color highlighting of the options in the options field.

I tried to modify the syntax to accomodate my fstab, but I'm a novice with vim syntax dsl don't actually understand why the options field is matched as in error, nor why it is so sensitive to the amount of whitespace. What's going on here?

**Comment by rid9** [comment]
Thank you for the report. `freq` and `passno` are now optional.

The update is part of version [1.6.3](https://github.com/rid9/vim-fstab/releases/tag/1.6.3a).
